# Generated by Django 5.0.3 on 2024-06-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestLogMarketPlaceApp', '0002_category_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='account_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
