# Generated by Django 5.0.3 on 2024-06-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestLogMarketPlaceApp', '0005_bankpaymentdetail_delete_bankpaymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpaymentdetail',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
