# Generated by Django 5.0.3 on 2024-06-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestLogMarketPlaceApp', '0006_bankpaymentdetail_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankpaymentdetail',
            old_name='display',
            new_name='active',
        ),
    ]
