# Generated by Django 5.0.3 on 2024-06-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestLogMarketPlaceApp', '0007_rename_display_bankpaymentdetail_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
